import { IconRobot, IconChartLine, IconCheck } from "@tabler/icons-react";
import { AurumMark } from "@/components/projects/BrandMarks";

/* ============================================================
   AURUM — AI Quarterly Report Composition
   Shows the AI generating a personalized client report
   ============================================================ */

const PARAGRAPHS = [
  {
    type: "para",
    text: 'Your portfolio outperformed the benchmark by 3.5 percentage points this quarter, driven primarily by overweight positions in <em>technology</em> and <em>healthcare</em>.',
  },
  {
    type: "stat",
    label: "Total return Q1",
    value: "+11.7%",
    sub: "Benchmark: +8.2%",
  },
  {
    type: "para",
    text: "Volatility remained moderate. Your downside exposure was protected by the alternatives allocation that we expanded in December.",
  },
  {
    type: "list",
    items: [
      "Equities (+13.2%) — outperformed S&P 500 by 280 bps",
      "Fixed Income (+5.8%) — duration positioning worked well",
      "Alternatives (+9.4%) — private credit exceeded expectations",
    ],
  },
  {
    type: "para",
    text: "Looking ahead to Q2, we recommend three tactical adjustments. We will discuss these at our scheduled review on May 23rd.",
  },
];

export function ScreenReport() {
  return (
    <div
      className="w-full h-full flex flex-col relative"
      style={{
        background:
          "radial-gradient(ellipse 70% 50% at 30% -10%, rgba(245,158,11,0.10), transparent 60%), linear-gradient(180deg, #0E0A04 0%, #06030B 100%)",
      }}
    >
      <div
        aria-hidden="true"
        className="absolute pointer-events-none"
        style={{
          top: -40,
          right: -40,
          width: 240,
          height: 240,
          background: "radial-gradient(circle, rgba(245,158,11,0.16), transparent 70%)",
          filter: "blur(40px)",
        }}
      />

      <div
        className="relative flex items-center justify-between px-4 py-2.5 border-b backdrop-blur-sm"
        style={{
          background: "rgba(20,14,5,0.85)",
          borderColor: "rgba(245,158,11,0.18)",
        }}
      >
        <div className="flex items-center gap-2">
          <span className="text-white text-[12px] font-semibold tracking-tight">
            Q1 2025 — Chen Family
          </span>
          <span
            className="text-[9px] uppercase tracking-wider px-1.5 py-0.5 rounded font-medium inline-flex items-center gap-1"
            style={{
              background: "rgba(245,158,11,0.12)",
              color: "#FBBF24",
              border: "1px solid rgba(245,158,11,0.25)",
            }}
          >
            <IconRobot size={9} stroke={2} />
            AI drafting
          </span>
        </div>
        <span
          className="text-[9px] font-mono"
          style={{ color: "#A89968" }}
        >
          Generated by Claude · reviewed by Eduard
        </span>
      </div>

      <main className="relative flex-1 grid grid-cols-1 lg:grid-cols-[1.5fr_1fr] gap-2.5 p-3 overflow-hidden min-h-0">
        {/* Generated report */}
        <article
          className="rounded-xl p-4 border relative overflow-hidden"
          style={{
            background:
              "linear-gradient(180deg, rgba(245,242,235,0.97) 0%, rgba(235,228,210,0.92) 100%)",
            borderColor: "rgba(245,158,11,0.22)",
            color: "#1f1408",
          }}
        >
          {/* Letterhead */}
          <div
            className="flex items-center justify-between pb-3 mb-3 border-b"
            style={{ borderColor: "rgba(31,20,8,0.15)" }}
          >
            <div className="flex items-center gap-2">
              <div
                className="w-5 h-5 rounded-full"
                style={{
                  background:
                    "linear-gradient(135deg, #F59E0B 0%, #B45309 100%)",
                }}
              />
              <span
                className="font-bold tracking-[0.2em] text-[12px]"
                style={{ color: "#B45309" }}
              >
                AURUM
              </span>
            </div>
            <span className="text-[8px] font-mono" style={{ color: "#5a4a28" }}>
              CONFIDENTIAL · Q1 2025
            </span>
          </div>

          <h2
            className="font-bold text-[15px] tracking-tight leading-tight"
            style={{ color: "#1f1408" }}
          >
            Quarterly Portfolio Review — Chen Family
          </h2>
          <p className="text-[9px] mt-1" style={{ color: "#5a4a28" }}>
            Prepared by Eduard Mercier · Senior Wealth Advisor
          </p>

          <div className="mt-3 space-y-2">
            {PARAGRAPHS.map((p, i) => {
              if (p.type === "para") {
                return (
                  <p
                    key={i}
                    className="text-[10px] leading-[1.55]"
                    style={{ color: "#2a1f0e" }}
                    dangerouslySetInnerHTML={{ __html: p.text! }}
                  />
                );
              }
              if (p.type === "stat") {
                return (
                  <div
                    key={i}
                    className="rounded-md border p-2 inline-flex flex-col"
                    style={{
                      background: "rgba(245,158,11,0.08)",
                      borderColor: "rgba(245,158,11,0.25)",
                    }}
                  >
                    <span className="text-[8px] uppercase tracking-wider" style={{ color: "#5a4a28" }}>
                      {p.label}
                    </span>
                    <span
                      className="text-lg font-bold tabular-nums leading-none mt-0.5"
                      style={{ color: "#B45309" }}
                    >
                      {p.value}
                    </span>
                    <span className="text-[8px] mt-0.5" style={{ color: "#5a4a28" }}>
                      {p.sub}
                    </span>
                  </div>
                );
              }
              return (
                <ul key={i} className="space-y-1 pl-3">
                  {p.items!.map((it, j) => (
                    <li
                      key={j}
                      className="text-[10px] leading-snug flex items-start gap-2"
                      style={{ color: "#2a1f0e" }}
                    >
                      <span
                        className="w-1 h-1 rounded-full shrink-0 mt-1.5"
                        style={{ background: "#B45309" }}
                      />
                      {it}
                    </li>
                  ))}
                </ul>
              );
            })}
          </div>

          <div
            className="mt-3 pt-2.5 border-t"
            style={{ borderColor: "rgba(31,20,8,0.15)" }}
          >
            <p className="text-[8px]" style={{ color: "#5a4a28" }}>
              This report is generated by AURUM&apos;s AI reporting system and reviewed by your wealth advisor before delivery.
            </p>
          </div>
        </article>

        {/* AI workflow log */}
        <aside
          className="rounded-xl p-3 border relative overflow-hidden flex flex-col min-h-0"
          style={{
            background:
              "linear-gradient(180deg, rgba(20,14,5,0.92) 0%, rgba(15,10,3,0.6) 100%)",
            borderColor: "rgba(245,158,11,0.15)",
            backdropFilter: "blur(8px)",
          }}
        >
          <div className="flex items-center justify-between mb-2.5">
            <div className="flex items-center gap-1.5">
              <div
                className="inline-flex items-center justify-center w-5 h-5 rounded-md"
                style={{
                  background: "rgba(245,158,11,0.15)",
                  border: "1px solid rgba(245,158,11,0.25)",
                }}
              >
                <IconChartLine size={10} stroke={1.5} color="#F59E0B" />
              </div>
              <span className="text-white text-[11px] font-semibold tracking-tight">
                Generation log
              </span>
            </div>
            <span className="text-[8px] font-mono" style={{ color: "#A89968" }}>
              23s total
            </span>
          </div>

          <ul className="space-y-2 text-[10px]">
            {[
              { ok: true, text: "Pulled holdings from custodian (4 accounts)" },
              { ok: true, text: "Computed performance vs S&P 500" },
              { ok: true, text: "Generated narrative · client voice match 94%" },
              { ok: true, text: "Compliance disclosures · auto-attached" },
              { ok: true, text: "Eduard reviewed · 2 edits applied" },
              { ok: true, text: "PDF generated · ready to send" },
            ].map((s, i) => (
              <li key={i} className="flex items-start gap-2">
                <div
                  className="shrink-0 w-4 h-4 rounded-full inline-flex items-center justify-center mt-0.5"
                  style={{
                    background: "rgba(16,185,129,0.18)",
                    border: "1px solid rgba(16,185,129,0.30)",
                  }}
                >
                  <IconCheck size={8} stroke={2.5} color="#34D399" />
                </div>
                <span style={{ color: "#cda66e" }}>{s.text}</span>
              </li>
            ))}
          </ul>

          <div
            className="mt-auto pt-3 rounded-md p-2 border"
            style={{
              background: "rgba(245,158,11,0.06)",
              borderColor: "rgba(245,158,11,0.18)",
            }}
          >
            <div className="flex items-center gap-1.5">
              <span
                className="w-1.5 h-1.5 rounded-full"
                style={{
                  background: "#10B981",
                  boxShadow: "0 0 4px #10B981",
                }}
              />
              <span className="text-[9px] font-medium" style={{ color: "#FBBF24" }}>
                Ready for client delivery
              </span>
            </div>
            <p
              className="text-[8px] mt-1 leading-snug"
              style={{ color: "#A89968" }}
            >
              Scheduled to send Mon, May 19 at 09:00 EST
            </p>
          </div>
        </aside>
      </main>
    </div>
  );
}
